
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    pods: "10"
    configmaps: "5"
    persistentvolumeclaims: "4"
    replicationcontrollers: "10"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
